/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaylistRouteImport } from './routes/playlist'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StagesIndexRouteImport } from './routes/stages/index'
import { Route as StagesStageIndexRouteImport } from './routes/stages/$stage/index'
import { Route as StagesStageModuleModuleRouteImport } from './routes/stages/$stage/module/$module'

const PlaylistRoute = PlaylistRouteImport.update({
  id: '/playlist',
  path: '/playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StagesIndexRoute = StagesIndexRouteImport.update({
  id: '/stages/',
  path: '/stages/',
  getParentRoute: () => rootRouteImport,
} as any)
const StagesStageIndexRoute = StagesStageIndexRouteImport.update({
  id: '/stages/$stage/',
  path: '/stages/$stage/',
  getParentRoute: () => rootRouteImport,
} as any)
const StagesStageModuleModuleRoute = StagesStageModuleModuleRouteImport.update({
  id: '/stages/$stage/module/$module',
  path: '/stages/$stage/module/$module',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playlist': typeof PlaylistRoute
  '/stages/': typeof StagesIndexRoute
  '/stages/$stage/': typeof StagesStageIndexRoute
  '/stages/$stage/module/$module': typeof StagesStageModuleModuleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playlist': typeof PlaylistRoute
  '/stages': typeof StagesIndexRoute
  '/stages/$stage': typeof StagesStageIndexRoute
  '/stages/$stage/module/$module': typeof StagesStageModuleModuleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playlist': typeof PlaylistRoute
  '/stages/': typeof StagesIndexRoute
  '/stages/$stage/': typeof StagesStageIndexRoute
  '/stages/$stage/module/$module': typeof StagesStageModuleModuleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playlist'
    | '/stages/'
    | '/stages/$stage/'
    | '/stages/$stage/module/$module'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playlist'
    | '/stages'
    | '/stages/$stage'
    | '/stages/$stage/module/$module'
  id:
    | '__root__'
    | '/'
    | '/playlist'
    | '/stages/'
    | '/stages/$stage/'
    | '/stages/$stage/module/$module'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaylistRoute: typeof PlaylistRoute
  StagesIndexRoute: typeof StagesIndexRoute
  StagesStageIndexRoute: typeof StagesStageIndexRoute
  StagesStageModuleModuleRoute: typeof StagesStageModuleModuleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playlist': {
      id: '/playlist'
      path: '/playlist'
      fullPath: '/playlist'
      preLoaderRoute: typeof PlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stages/': {
      id: '/stages/'
      path: '/stages'
      fullPath: '/stages/'
      preLoaderRoute: typeof StagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stages/$stage/': {
      id: '/stages/$stage/'
      path: '/stages/$stage'
      fullPath: '/stages/$stage/'
      preLoaderRoute: typeof StagesStageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stages/$stage/module/$module': {
      id: '/stages/$stage/module/$module'
      path: '/stages/$stage/module/$module'
      fullPath: '/stages/$stage/module/$module'
      preLoaderRoute: typeof StagesStageModuleModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaylistRoute: PlaylistRoute,
  StagesIndexRoute: StagesIndexRoute,
  StagesStageIndexRoute: StagesStageIndexRoute,
  StagesStageModuleModuleRoute: StagesStageModuleModuleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
