server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /videos/ {
        proxy_pass http://server:8888/videos/;
    }

    location /backup {
        proxy_pass http://server:8888/backup;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}